# bgs from https://noranekogames.itch.io/yumebackground
image bg apartment_exterior = "images/backgrounds/Apartment_Exterior.png"
image bg apartment_exterior_night = "images/backgrounds/Apartment_Exterior_Night.png"
image bg bathroom = "images/backgrounds/Bathroom.png"
image bg bathroom_foggy = "images/backgrounds/Bathroom_Foggy.png"
image bg bedroom_day = "images/backgrounds/Bedroom_Day.png"
image bg bedroom_evening = "images/backgrounds/Bedroom_Evening.png"
image bg bedroom_night = "images/backgrounds/Bedroom_Night.png"
image bg bedroom_night_dark = "images/backgrounds/Bedroom_Night_Dark.png"
image bg cafeteria_day = "images/backgrounds/Cafeteria_Day.png"
image bg city_afternoon = "images/backgrounds/City_Afternoon.png"
image bg city_morning = "images/backgrounds/City_Morning.png"
image bg city_night = "images/backgrounds/City_Night.png"
image bg city_raining = "images/backgrounds/City_Raining.png"
image bg classroom_day = "images/backgrounds/Classroom_Day.png"
image bg futon_room = "images/backgrounds/Futon_Room.png"
image bg futon_room_night = "images/backgrounds/Futon_Room_Night.png"
image bg kitchen_day = "images/backgrounds/Kitchen_Day.png"
image bg kitchen_night = "images/backgrounds/Kitchen_Night.png"
image bg laundromat = "images/backgrounds/Laundromat.png"
image bg living_room_dark = "images/backgrounds/Livingroom_Dark.png"
image bg living_room_day = "images/backgrounds/Livingroom_Day.png"
image bg living_room_night = "images/backgrounds/Livingroom_Night.png"
image bg onsen_building = "images/backgrounds/Onsen_Building.png"
image bg onsen_building_night = "images/backgrounds/Onsen_Building_Night.png"
image bg outdoor_stairs = "images/backgrounds/Outdoor_Stairs.png"
image bg restaurant_a = "images/backgrounds/Restaurant_A.png"
image bg restaurant_b = "images/backgrounds/Restaurant_B.png"
image bg school_hallway_day = "images/backgrounds/School_Hallway_Day.png"
image bg sitting_room = "images/backgrounds/Sitting_Room.png"
image bg sitting_room_dark = "images/backgrounds/Sitting_Room_Dark.png"
image bg apartment_kitchen = "images/backgrounds/Small_Apartment_Kitchen.png"
image bg apartment_kitchen_night = "images/backgrounds/Small_Apartment_Kitchen_Night.png"
image bg street_autumn_day = "images/backgrounds/Street_Autumn_Day.png"
image bg street_autumn_evening = "images/backgrounds/Street_Autumn_Evening.png"
image bg street_autumn_night = "images/backgrounds/Street_Autumn_Night.png"
image bg street_spring_day = "images/backgrounds/Street_Spring_Day.png"
image bg street_spring_evening = "images/backgrounds/Street_Spring_Evening.png"
image bg street_spring_night = "images/backgrounds/Street_Spring_Night.png"
image bg street_spring_rain = "images/backgrounds/Street_Spring_Rain.png"
image bg street_summer_day = "images/backgrounds/Street_Summer_Day.png"
image bg street_summer_evening = "images/backgrounds/Street_Summer_Evening.png"
image bg street_summer_night = "images/backgrounds/Street_Summer_Night.png"
image bg street_summer_rain = "images/backgrounds/Street_Summer_Rain.png"
image bg street_summer_stars = "images/backgrounds/Street_Summer_Stars.png"
image bg train_beach = "images/backgrounds/Train_beach.png"
image bg train_day = "images/backgrounds/Train_Day.png"
image bg train_day_rain = "images/backgrounds/Train_Day_Rain.png"
image bg train_evening = "images/backgrounds/Train_Evening.png"
image bg train_night = "images/backgrounds/Train_Night.png"
image bg train_night_rain = "images/backgrounds/Train_Night_Rain.png"
image bg train_tunnel = "images/backgrounds/Train_Tunnel.png"
image bg office_day:
    "images/backgrounds/office_day.jpg"
    zoom 2.5

image white = Solid("#fff")